# nimble test on macOS, for each push and pull request (nimble-test.yml). A change to only
# the docs, the license or editor settings doesn't run it.
name: macOS

on:
  push:
    paths-ignore: ['**.md', 'LICENSE', '.vscode/**']
  pull_request:
    paths-ignore: ['**.md', 'LICENSE', '.vscode/**']

jobs:
  test:
    uses: ./.github/workflows/nimble-test.yml
    with:
      os: macos-latest
